{
 "title": "NODE EXPORTER",
 "tags": [
  "NODE",
  "PROMETHEUS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "CPU name",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env'},name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_exporter_build_info{name='$name'},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs|btrfs\"}) by (mountpoint))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total disk space",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs|fuse|zfs|btrfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "The average system load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Audit number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Root partition usage",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Maximum partition ($maxmount) usage",
   "type": "grafana-singlestat-panel",
   "description": "Get the largest partition by the variable maxmount. ",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs|zfs|btrfs|fuse\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs|btrfs|fuse\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs|btrfs|fuse\"})"
    },
    {}
   ]
  },
  {
   "title": "CPU usage（5m）",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "Currently open file descriptor",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out upload"
    }
   ]
  },
  {
   "title": "CPU usage, disk I/O operations per second take time（%）",
   "type": "timeseries",
   "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value.（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is, the percentage of time that the disk spends on I/O operations in 1 second.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_% of I/O operations per second"
    }
   ]
  },
  {
   "title": "Memory information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "timeseries",
   "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk read and write capacity",
   "type": "timeseries",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk read and write rate（IOPS）",
   "type": "timeseries",
   "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "timeseries",
   "description": "CurrEstab - TCP connections with current state ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from CLOSED state to SYN-SENT state (within 1 minute)\n\nPassiveOpens - Directly from LISTEN state The average number of TCP connections to SYN-RCVD state (within 1 minute)\n\nTCP_all oc - the number of TCP sockets allocated (established, applied to sk_buff)\n\nTCP_inuse - in use (listening The number of TCP sockets \n\nTCP_tw - the number of TCP connections waiting to be closed",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "Hardware temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  }
 ]
}